# apps/intelligence/src/ade/enums.py
from enum import Enum


class ADEDecisionType(str, Enum):
  NO_ACTION = "NO_ACTION"
  GENERATE_LEARNING_EXPERIENCE = "GENERATE_LEARNING_EXPERIENCE"
  REGENERATE_LEARNING_EXPERIENCE = "REGENERATE_LEARNING_EXPERIENCE"
  ADJUST_DIFFICULTY = "ADJUST_DIFFICULTY"
  REDUCE_LOAD = "REDUCE_LOAD"
  INCREASE_LOAD = "INCREASE_LOAD"
  ADD_REMEDIATION = "ADD_REMEDIATION"
  INCREASE_PRACTICE = "INCREASE_PRACTICE"
  CHANGE_SEQUENCE = "CHANGE_SEQUENCE"
  REASSESS_READINESS = "REASSESS_READINESS"
  REASSESS_TRAJECTORY = "REASSESS_TRAJECTORY"
  PAUSE_LEARNING_PATH = "PAUSE_LEARNING_PATH"
  RESUME_LEARNING_PATH = "RESUME_LEARNING_PATH"
  CHANGE_TOPIC = "CHANGE_TOPIC"
  CHANGE_ACTIVE_GOAL = "CHANGE_ACTIVE_GOAL"
  CHANGE_CAREER_TARGET = "CHANGE_CAREER_TARGET"
  ABANDON_LEARNING_PATH = "ABANDON_LEARNING_PATH"


class ImpactLevel(str, Enum):
  LOW = "LOW"
  MEDIUM = "MEDIUM"
  HIGH = "HIGH"
  CRITICAL = "CRITICAL"


class DecisionStatus(str, Enum):
  PROPOSED = "PROPOSED"
  VALIDATED = "VALIDATED"
  APPROVAL_PENDING = "APPROVAL_PENDING"
  APPROVED = "APPROVED"
  REJECTED = "REJECTED"
  DISPATCHED = "DISPATCHED"
  EXECUTING = "EXECUTING"
  COMPLETED = "COMPLETED"
  PARTIAL_SUCCESS = "PARTIAL_SUCCESS"
  FAILED = "FAILED"
  INVALIDATED = "INVALIDATED"
  EXPIRED = "EXPIRED"
  CANCELLED = "CANCELLED"
  TIMEOUT = "TIMEOUT"


class ApprovalStatus(str, Enum):
  NOT_REQUIRED = "NOT_REQUIRED"
  PENDING = "PENDING"
  APPROVED = "APPROVED"
  REJECTED = "REJECTED"
  EXPIRED = "EXPIRED"


class ExecutionStatus(str, Enum):
  PENDING = "PENDING"
  ACCEPTED = "ACCEPTED"
  STARTED = "STARTED"
  SUCCESS = "SUCCESS"
  PARTIAL_SUCCESS = "PARTIAL_SUCCESS"
  FAILED = "FAILED"
  TIMEOUT = "TIMEOUT"


class Executor(str, Enum):
  MIE = "MIE"
  RIE = "RIE"
  CIE = "CIE"
  NONE = "NONE"


class ADEEventType(str, Enum):
  ADAPTATION_DECIDED = "ADAPTATION_DECIDED"
  ADAPTATION_APPROVAL_REQUESTED = "ADAPTATION_APPROVAL_REQUESTED"
  ADAPTATION_APPROVED = "ADAPTATION_APPROVED"
  ADAPTATION_REJECTED = "ADAPTATION_REJECTED"
  ADAPTATION_EXPIRED = "ADAPTATION_EXPIRED"
  ADAPTATION_DISPATCHED = "ADAPTATION_DISPATCHED"
  ADAPTATION_EXECUTION_STARTED = "ADAPTATION_EXECUTION_STARTED"
  ADAPTATION_COMPLETED = "ADAPTATION_COMPLETED"
  ADAPTATION_FAILED = "ADAPTATION_FAILED"
  ADAPTATION_TIMEOUT = "ADAPTATION_TIMEOUT"
  DECISION_INVALIDATED = "DECISION_INVALIDATED"
  DECISION_CANCELLED = "DECISION_CANCELLED"