# apps/intelligence/src/upe/enums.py
from enum import Enum


class ProgressBand(str, Enum):
    VERY_LOW = "VERY_LOW"
    LOW = "LOW"
    MODERATE = "MODERATE"
    STRONG = "STRONG"
    VERY_STRONG = "VERY_STRONG"


class VelocityTrendDirection(str, Enum):
    ACCELERATING = "ACCELERATING"
    STABLE = "STABLE"
    SLOWING = "SLOWING"
    INSUFFICIENT_HISTORY = "INSUFFICIENT_HISTORY"


class ProgressTrendDirection(str, Enum):
    IMPROVING = "IMPROVING"
    STABLE = "STABLE"
    DECLINING = "DECLINING"
    INSUFFICIENT_HISTORY = "INSUFFICIENT_HISTORY"


class CapabilityProgressTrend(str, Enum):
    IMPROVING = "IMPROVING"
    STABLE = "STABLE"
    REGRESSING = "REGRESSING"
    INSUFFICIENT_HISTORY = "INSUFFICIENT_HISTORY"


class ProgressSignalType(str, Enum):
    CAPABILITY_STATE_CHANGED = "CAPABILITY_STATE_CHANGED"
    LEARNING_STEP_COMPLETED = "LEARNING_STEP_COMPLETED"
    PROJECT_SUBMITTED = "PROJECT_SUBMITTED"
    ASSESSMENT_COMPLETED = "ASSESSMENT_COMPLETED"
    LEARNING_EXPERIENCE_COMPLETED = "LEARNING_EXPERIENCE_COMPLETED"