# apps/intelligence/src/mie/enums.py
from enum import Enum


class ExperienceStatus(str, Enum):
    DRAFT = "DRAFT"
    GENERATED = "GENERATED"
    AVAILABLE = "AVAILABLE"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"


class StepType(str, Enum):
    RESOURCE = "RESOURCE"
    PROJECT = "PROJECT"
    ASSESSMENT = "ASSESSMENT"


class ResourceType(str, Enum):
    VIDEO = "VIDEO"
    DOCUMENTATION = "DOCUMENTATION"
    ARTICLE = "ARTICLE"
    TUTORIAL = "TUTORIAL"
    REFERENCE = "REFERENCE"


class ResourceValidationStatus(str, Enum):
    PENDING = "PENDING"
    VALID = "VALID"
    INVALID = "INVALID"
    EXPIRED = "EXPIRED"
    UNAVAILABLE = "UNAVAILABLE"


class ProjectStatus(str, Enum):
    DRAFT = "DRAFT"
    AVAILABLE = "AVAILABLE"
    IN_PROGRESS = "IN_PROGRESS"
    SUBMITTED = "SUBMITTED"
    EVALUATING = "EVALUATING"
    COMPLETED = "COMPLETED"


class AssessmentType(str, Enum):
    MCQ = "MCQ"
    SHORT_ANSWER = "SHORT_ANSWER"
    SCENARIO = "SCENARIO"
    CODE_OUTPUT = "CODE_OUTPUT"


class AssessmentStatus(str, Enum):
    DRAFT = "DRAFT"
    GENERATED = "GENERATED"
    VALIDATED = "VALIDATED"
    AVAILABLE = "AVAILABLE"
    IN_PROGRESS = "IN_PROGRESS"
    SUBMITTED = "SUBMITTED"
    EVALUATING = "EVALUATING"
    EVALUATED = "EVALUATED"
    INVALID = "INVALID"
    EXPIRED = "EXPIRED"
    ABANDONED = "ABANDONED"


class MIEEventType(str, Enum):
    LEARNING_EXPERIENCE_GENERATED = "LEARNING_EXPERIENCE_GENERATED"
    LEARNING_EXPERIENCE_STARTED = "LEARNING_EXPERIENCE_STARTED"
    LEARNING_STEP_STARTED = "LEARNING_STEP_STARTED"
    LEARNING_STEP_COMPLETED = "LEARNING_STEP_COMPLETED"
    PROJECT_SUBMITTED = "PROJECT_SUBMITTED"
    ASSESSMENT_COMPLETED = "ASSESSMENT_COMPLETED"
    LEARNING_EXPERIENCE_COMPLETED = "LEARNING_EXPERIENCE_COMPLETED"